### ISSUE TITLE
NestJS Docker Container Fails to Start

### ISSUE THREAD

**Issue by SoftwareDevRamiro** [SoftwareDevRamiro/nestjs-rabbitmq-microservice#1]
Description: Despite following the setup instructions provided in the README.md file, attempts to run the NestJS application inside a Docker container result in a failure to start the container, rendering the application inaccessible.

Expected Behavior: The Docker container should start successfully, allowing access to the NestJS application as described in the repository's documentation.

Actual Behavior: The Docker container fails to start, and accessing the application endpoint yields an error message, suggesting an issue with the Docker configuration or dependencies within the repository.

**Comment by kinperakey** [comment]
> Description: Despite following the setup instructions provided in the README.md file, attempts to run the NestJS application inside a Docker container result in a failure to start the container, rendering the application inaccessible.
> 
> Expected Behavior: The Docker container should start successfully, allowing access to the NestJS application as described in the repository's documentation.
> 
> Actual Behavior: The Docker container fails to start, and accessing the application endpoint yields an error message, suggesting an issue with the Docker configuration or dependencies within the repository.

To resolve the issue, I recommend checking the Dockerfile and docker-compose.yml for any misconfigurations, ensuring that the necessary dependencies are properly installed and the application's ports are correctly exposed. Additionally, verifying that the NestJS application is built and compiled correctly before running the Docker container might help troubleshoot the startup failure.

**Comment by SoftwareDevRamiro** [comment]
Awesome
